version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `pnpm-lock.yaml` in the root directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
      time: "00:00"
    # Customize pull request settings
    commit-message:
      prefix: "chore"
      include: "scope"
    # Limit the number of open pull requests Dependabot can have at any time
    open-pull-requests-limit: 10
    # Allow version updates that do not include breaking changes
    # You can adjust this to "all" if you want to receive updates for major versions
    versioning-strategy: "increase-if-necessary"
  - package-ecosystem: "github-actions" # Check for updates to GitHub Actions
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
